### ISSUE TITLE
После запуска контейнера открываю сайт http://localhost:8000/ получаю ошибку Array['errMessage'], что делать?

### ISSUE THREAD

**Issue by Nephedov** [mshegolev/congenial-potato#3]
Добавьте в скрипт https://github.com/mshegolev/congenial-potato/blob/main/cinema/BD/id11870327_mysite.sql предварительное удаление таблиц и ограничений, перед созданием новых.

Предварительные действия:
 - Открыть http://localhost:8081/ логин admin пароль test
 - Выбрать база данных database.
 - Перейти на вкладку SQL.
 - Открыть скрипт https://github.com/mshegolev/congenial-potato/blob/main/cinema/BD/id11870327_mysite.sql
 - Скопировать данные из скрипта и вставить в окно SQL.
 - Выполнить скрипт (нажать кнопку Вперед/Запустить в русской версии или run) Если с первого раза скрипт не выполнится, 
    то запустить повторно убедившись что подключились к базе данных database.
 - Открыть сайт http://localhost:8000/client/index.php убедиться что доступен выбор фильмов.

Суть проблемы:
 - При добавлении данного скрипта https://github.com/mshegolev/congenial-potato/blob/main/cinema/BD/id11870327_mysite.sql  , выскакивает ошибка о уже созданных ранее (но пустых, без данных) таблицах.
 - При ручном предварительном удалении всех таблиц и ограничений БД, - скрипт сработал как надо.

Windows 10.
Coogle Chrome Версия 115.0.5790.171 (Официальная сборка), (64 бит).
Docker Compose version v2.13.0

**Comment by mshegolev** [comment]
Добавлено удаление таблиц перед их созданием и проверка на созданные триггеры.
https://github.com/mshegolev/congenial-potato/blob/main/cinema/BD/id11870327_mysite.sql
-- удаляем таблицы если созданы
drop table `films`;
drop table `halls`;
drop table `sales`;
drop table `seances`;
drop table `users`;
